// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/Hints.tsx";
import * as $$1 from "./islands/Keyboard.tsx";
import * as $$2 from "./islands/MainGame.tsx";
import * as $$3 from "./islands/NumberBox.tsx";
import * as $$4 from "./islands/Wordle.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/Hints.tsx": $$0,
    "./islands/Keyboard.tsx": $$1,
    "./islands/MainGame.tsx": $$2,
    "./islands/NumberBox.tsx": $$3,
    "./islands/Wordle.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
